chances:
  #The chance of a melon growing
  melon: 1/4
  
  #The chance of a pumpkin growing
  pumpkin: 1/5
  
  #The chance of a nether wart growing
  netherWart: 1/1
  
  #The chance of a cactus growing
  cactus: 1/3
  
  #The chance of sugar cane growing
  sugarCane: 1/3
  
#Allow metrics logging
useMetrics: true

#Display update messages to player if they have the permission forcegrow.updates
checkForUpdates: true
