name: ForceGrow
main: com.electro2560.dev.ForceGrow.ForceGrow
version: 1.0.3
api-version: 1.13
author: ElectroBoy2560
website: https://dev.electro2560.com/
description: Force grow crops with bone meal!